### ISSUE TITLE
Add a zoom out camera feature like from the Gcam

### ISSUE THREAD

**Issue by MarkCyberSecDev93** [GrapheneOS/Camera#350] opened 2023-03-21 02:07 UTC
![signal-2023-03-21-10-09-08-811.jpg](https://user-images.githubusercontent.com/58934423/226503043-acf0e391-3dd7-4b1a-b188-1bc3d9407744.jpg)

**Comment by thestinger** [comment] 2023-03-21 02:09
How should we decide which zoom values to show? They show minimum zoom, 1x zoom and the base value where the telephoto lens can be used which we can't easily determine across devices. Also, their 4x zoom button on Pixel 6 Pro and Pixel 7 Pro often does not actually trigger switch to telephoto camera despite that being a common misconception because the zoom value it switches is dynamic and often is around 4.7x or 4.8x for typical lightning indoors, on a cloudy day or in the evening.

**Comment by thestinger** [comment] 2023-03-21 02:10
Duplicate of https://github.com/GrapheneOS/Camera/issues/87.

**Closed by thestinger** 2023-03-21 02:10 UTC

**Comment by MarkCyberSecDev93** [comment] 2023-03-21 02:15
Ok, I'll delete this issue as it has its own duplicates
