### ISSUE TITLE
Video resolution defaults to 4K

### ISSUE THREAD

**Issue by mariobrostech** [GrapheneOS/Camera#218] opened 2022-05-13 23:56 UTC
Seemingly randomly (but can most easily be replicated by force closing and restarting the camera using the shortcut from the lock screen), the GrapheneOS Camera will default to using 4K video resolution even after being overridden to 1080p. This issue appeared a few updates ago, but I didn’t notice it until recently, when I decided to review the footage I shot on a trip.

I am running a Pixel 5a with the latest stable release of GrapheneOS and Camera v36.

Thanks in advance for your help!

**Comment by mariobrostech** [comment] 2022-05-14 00:02
After looking into this more, the switch in resolutions doesn’t appear to take effect until the settings panel is opened. When this happens, the camera will adjust its cropping accordingly, indicating the resolution change.

**Comment by thestinger** [comment] 2022-05-14 00:25
Trying to reproduce this but I don't seem to be able to do it.

**Comment by mariobrostech** [comment] 2022-05-14 01:15
I was able to find a way to reliably reproduce this issue on my device. The steps I followed, as well as the result, can be seen in [this screen recording I made](https://we.tl/t-AUITMEW6Cd).

**Comment by thestinger** [comment] 2022-05-14 01:40
@mariobrostech We're able to reproduce it. I'm removing your comment since you might have accidentally included some personal info in the video.

**Comment by thestinger** [comment] 2022-05-14 01:46
The lockscreen settings are currently deliberately separate and are also temporary. The idea behind this was to stop people with access to the locked device being able to mess with your settings persistently.

**Comment by thestinger** [comment] 2022-05-14 01:46
Could it just be a side effect of that?

**Comment by mariobrostech** [comment] 2022-05-14 02:45
Possibly, but I’ve noticed this sometimes bleeding into the regular app’s settings as well (though I can’t find a reliable way to reproduce this in particular). Regardless, if the lock screen is using temporary settings, it should inherit those that are already set by the user (or, it should at least provide an option for this to be the case).

**Comment by thestinger** [comment] 2022-05-14 03:57
We could implement that instead of doing what we are right now.

**Comment by thestinger** [comment] 2022-05-19 08:13
Should be resolved by v38.

**Closed by thestinger** 2022-05-19 08:13 UTC
Labels: bug
