### ISSUE TITLE
Zoom buttons

### ISSUE THREAD

**Issue by popogomo** [GrapheneOS/Camera#336] opened 2023-01-08 12:37 UTC
Thanks for creating such an amazing OS and apps!

It is very challenging to use zoom, especially, the optical zoom, as we need to manually zoom in and out each time and its very hard to zoom in to the exact value (for example, 0.5x, 2x, 5x, etc)

Can you please add optical zoom buttons, just like in Google Camera app (wide 0.5x or 0.7x, normal (1x), optical zoom (2x, 5x, etc, depending on the model)? It will make using the app a way more easier and convenient.

As GOS is supported on different Pixel phones, each of them having their own optical zoom, the camera app can identify which phone model we use (Pixel 6, 7, etc) and add the optical zoom buttons accordingly, depending on profile. It should be fairly easy as there are only a few Pixel models so the app can have zoom values for each phone and apply these based on the phone user is using.

Alternatively, it can just have built-in profiles and users can select their phone from the profiles list to apply correct values.

Another solution would be allowing users to manually enter zoom values they want to use so the app will display these instead (for example, some users might prefer having 20x zoom available at hand). 

Thanks!

**Comment by thestinger** [comment] 2023-01-08 17:02
Pixel 6 Pro / Pixel 7 Pro have a 4x optical camera but it's not triggered at exactly 4x zoom. The level it's triggered varies significantly based on light level. It often triggers at 4.7x or higher in low light, or not at all.

**Comment by r3g-5z** [comment] 2023-01-08 18:09
Duplicate of https://github.com/GrapheneOS/Camera/issues/87

**Closed by r3g-5z** 2023-01-08 18:09 UTC
