### ISSUE TITLE
Add support for digital video stabilization

### ISSUE THREAD

**Issue by pluja** [GrapheneOS/Camera#34] opened 2021-10-21 08:00 UTC
Google Camera has support for digital video stabilization. This is pretty good on devices like Pixel 3a. 

I don't know how difficult is this. Could this be implemented?

**Comment by MHShetty** [comment] 2021-11-19 00:06
The issue filed by me seems to be a duplicate of another existing issue.

This link can be used to track the issue now: https://issuetracker.google.com/issues/172946955

**Comment by Staysafe2022** [comment] 2021-12-23 12:41
Thanks for working on it , hopefully one day supported.

**Comment by thestinger** [comment] 2022-05-19 23:37
This is implemented via the Camera2 interop API.

**Closed by thestinger** 2022-05-19 23:37 UTC
Labels: enhancement, priority-medium
